name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: cmake-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest]
        cuda-version: ['11.8', '12.1']
        build_type: [Release]
        variant: [CUDA, NOBLASLT, CPU]

    steps:
    - uses: actions/checkout@v4

    - name: Set up MSVC
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1.12.1
      with:
        arch: amd64

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Prepare
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        if [ "${{ matrix.cuda-version }}" = "11.8" ]; then
            echo "cuda-toolkit-version=11.8.0" >> "$GITHUB_OUTPUT"
        else
            echo "cuda-toolkit-version=12.1.1" >> "$GITHUB_OUTPUT"
        fi
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
            echo CXX_COMPILER=cl >> "$GITHUB_ENV"
            echo C_COMPILER=cl >> "$GITHUB_ENV"
            # without -DCMAKE_CUDA_COMPILER=nvcc, cmake config always fail for cuda-11.8
            echo DCMAKE_CUDA_COMPILER=-DCMAKE_CUDA_COMPILER=nvcc >> "$GITHUB_ENV"
        else
            echo CXX_COMPILER=g++ >> "$GITHUB_ENV"
            echo C_COMPILER=gcc >> "$GITHUB_ENV"
        fi
        if [ "${{ matrix.variant }}" = "CUDA" ]; then
            echo "cmake_args=" >> "$GITHUB_OUTPUT"
        elif [ "${{ matrix.variant }}" = "NOBLASLT" ]; then
            echo "cmake_args=-DNO_CUBLASLT=ON" >> "$GITHUB_OUTPUT"
        else if [ "${{ matrix.variant }}" = "CPU" ]; then
            echo "-DNO_CUBLASLT=ON -DBUILD_CUDA=OFF" >> "$GITHUB_OUTPUT"
        else
            echo "Unknown variant" && exit 1
        fi

    - uses: Jimver/cuda-toolkit@v0.2.14
      name: Install CUDA Toolkit ${{ steps.strings.outputs.cuda-toolkit-version }}
      with:
        cuda: ${{ steps.strings.outputs.cuda-toolkit-version }}

    - name: Prep build
      run: python -m pip install cmake==3.27.9 ninja setuptools wheel

    - name: Configure
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -G Ninja ${{ env.DCMAKE_CUDA_COMPILER }}
        -DCMAKE_CXX_COMPILER=${{ env.CXX_COMPILER }}
        -DCMAKE_C_COMPILER=${{ env.C_COMPILER }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DCOMPUTE_CAPABILITY="50;52;60;61;62;70;72;75;80;86;87;89;90"
        ${{ steps.strings.outputs.cmake_args }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - run: ls -laR

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4.3.0
      with:
        name: bitsandbytes-${{ matrix.os }}-${{ matrix.cuda-version }}-${{ matrix.variant }}
        path: |
          ${{ github.workspace }}/build/
